trigger:
  - test_branch
pool:
  name: Default
  Agent: LVDMS-PROD-IR-SH
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: Use Python $(python.version)
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: Install dependencies
  - script: |
      pip install pytest pytest-azurepipelines pytest-csv
      pytest --csv=report.csv --csv-columns=id,status,duration,name
    displayName: Run tests with pytest and generate CSV report
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      Contents: '*/'
      TargetFolder: $(Build.ArtifactStagingDirectory)
    displayName: Copy files to artifact staging directory
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: dist
      publishLocation: Container

variables:
  APP_USERNAME: $(your_username_variable)
  APP_PASSWORD: $(your_password_variable)
