trigger:
  - develop
pool:
  name: Default
  Agent: LVDMS-PROD-IR-SH
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: Use Python $(python.version)
  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'LVDMS-DEV-UAT-WIF'
      KeyVaultName: lv-map-temp-kv
      SecretsFilter: '*'
    displayName: Fetch secrets from Azure Key Vault
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: Install dependencies
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)\reports
    displayName: create reports directory
  - script: |
      pytest --html=$(Build.ArtifactStagingDirectory)\reports\test_report.html
    displayName: Run Pytest and Generate Reports
      # Copy the report to artifact staging directory
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.ArtifactStagingDirectory)/reports
      Contents: '*'
      TargetFolder: $(System.DefaultWorkingDirectory)/reports
    displayName: Copy reports to artifact staging directory

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/reports
      ArtifactName: reports
      publishLocation: Container
